# Q1. What is the total revenue generated by male vs. female customers?

Select gender,sum(purchase_amount) as revenue
from customer
group by gender;



#  Q2. Which customers used a discount but still spent more than the average purchase amount? 

Select customer_id
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer);



#  Q3. Which are the top 5 products with the highest average review rating?

Select item_purchased,round(avg(review_rating),2) as avg_review_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


# Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

Select shipping_type,round(avg(purchase_amount),2) as avg_purchase_amount
from customer
where shipping_type='standard' or shipping_type='Express'
group by shipping_type;


# Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

Select subscription_status,count(customer_id) as customers ,round(avg(purchase_amount),2) as avg_spend,sum(purchase_amount) as total_revenue
from customer
group by subscription_status;


#  Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
round(sum(case when discount_applied='yes' then 1 else 0 end)/count(*) *100,2) as discounted_time
from customer
group by item_purchased	
order by discounted_time desc
limit 5;



#  Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

Select 
case
      when previous_purchases=1 then 'New'
      when previous_purchases between 2 and 10 then 'Returning'
      when previous_purchases > 10 then 'Loyal'
      end as customer_type,
      count(*) as total_customers
	from customer
    group by customer_type;

	
#  Q8. What are the top 3 most purchased products within each category?

with product_performance as (Select category,item_purchased,count(customer_id) as quantity
from customer
group by category,item_purchased
order by category,quantity desc)
,
ranking as (select category,item_purchased,
		row_number() over(partition by category order by quantity desc) as product_rank
        from product_performance)
        
select category,item_purchased
from ranking 
where product_rank between 1 and 3;

####   Other Approach -- Shorter and More organised __ less load on machine 

with product_performance as 
		(select category,item_purchased,count(customer_id) as quantity,
				row_number() over(partition by category order by count(customer_id) desc ) as product_rank
                from customer
                group by category,item_purchased
                )
                
		select product_rank,category,item_purchased,quantity
        from product_performance
        where product_rank<=3;
 


#  Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


	Select subscription_status,count(customer_id) as repeat_buyers
    from customer
    where previous_purchases>5
    group by subscription_status;
        
    
    
#  Q10. What is the revenue contribution of each age group? 

		Select age_group,sum(purchase_amount) as total_revenue
        from customer 
        group by age_group
        order by total_revenue desc